import React, { useMemo, useState } from 'react';
import { Brain, FileText, FolderTree, Headphones, Languages, MessageSquare, Mic, Moon, Sparkles, Sun, TabletSmartphone } from 'lucide-react';

const architectureLayers = [
  {
    title: 'Experience Layer (Web + iOS + Android)',
    points: [
      'Next.js web app with React Native mobile clients sharing design tokens and business logic.',
      'Offline-first local cache for notes, flashcards, and generated quizzes using IndexedDB/SQLite.',
      'Realtime collaboration UI via CRDT-powered editor components and sync presence indicators.',
    ],
  },
  {
    title: 'Application Layer',
    points: [
      'Node.js API gateway (REST + WebSocket) orchestrates AI workflows, auth, and user state.',
      'Feature services: Capture Service, Notes Service, Study Suite Service, Collaboration Service, Export Service.',
      'Background queue workers handle heavy jobs (transcription, podcast rendering, PDF generation).',
    ],
  },
  {
    title: 'AI + Data Layer',
    points: [
      'OpenAI/Whisper for speech-to-text, summarization, and question generation pipelines.',
      'TTS provider for study podcasts with selectable voice styles + playback metadata.',
      'Primary DB (PostgreSQL/Firebase), object storage for files/audio, vector index for contextual AI chat.',
    ],
  },
];

const sampleScreens = [
  {
    title: 'Dashboard',
    subtitle: 'Sidebar-first productivity hub',
    items: ['Smart folders by subject', 'Upcoming quizzes + streaks', 'Recent recordings and exports'],
  },
  {
    title: 'Notes Studio',
    subtitle: 'Notion-like editor + AI assistant',
    items: ['Structured transcript (headings, bullets, definitions)', 'Auto-highlighted key terms', 'One-click “simplify creatively” actions'],
  },
  {
    title: 'Quiz Arena',
    subtitle: 'Adaptive practice engine',
    items: ['Unlimited MCQ and short-answer generation', 'Instant feedback with reasoning', 'Spaced repetition heatmap + mastery score'],
  },
  {
    title: 'Tutor Chat',
    subtitle: 'Context-aware side panel',
    items: ['Answers grounded in user notes/docs', '“Explain like sports practice” prompts', 'Inline citations and follow-up cards'],
  },
];

const pdfFlow = [
  'Collect cleaned structured notes + extracted definitions + comparisons.',
  'Apply user-selected theme (pastel, dark, neon, school-style).',
  'Compose sections with title page, dividers, keyword highlights, and summary boxes.',
  'Render print-optimized PDF (A4 + US Letter support) and downloadable assets.',
];

const codeSnippet = `import PDFDocument from 'pdfkit';

export async function generateStyledStudyGuide(payload) {
  const doc = new PDFDocument({ size: 'A4', margins: { top: 56, left: 48, right: 48, bottom: 56 } });
  const theme = themes[payload.theme ?? 'pastel'];

  // Title page
  doc.rect(0, 0, doc.page.width, doc.page.height).fill(theme.background);
  doc.fillColor(theme.primary).font('Helvetica-Bold').fontSize(34).text(payload.title, 48, 180);
  doc.fillColor(theme.text).fontSize(14).text('Generated by StudyTurbo', 48, 230);
  doc.addPage();

  payload.sections.forEach((section, i) => {
    doc.fillColor(theme.sectionColors[i % theme.sectionColors.length])
      .font('Helvetica-Bold')
      .fontSize(20)
      .text(section.heading, { underline: true });

    section.bullets.forEach((bullet) => {
      doc.fillColor(theme.text).font('Helvetica').fontSize(12).text('• ' + bullet, { indent: 16 });
    });

    section.definitions.forEach((def) => {
      doc.roundedRect(48, doc.y + 8, 500, 54, 8).fill(theme.definitionBox);
      doc.fillColor(theme.text).font('Helvetica-Bold').text(def.term, 60, doc.y - 48);
      doc.font('Helvetica').text(def.meaning, 60, doc.y + 4, { width: 470 });
      doc.moveDown(2);
    });
  });

  doc.end();
  return doc;
}`;

export default function App() {
  const [darkMode, setDarkMode] = useState(true);

  const theme = useMemo(
    () =>
      darkMode
        ? {
            page: 'bg-slate-950 text-slate-100',
            card: 'bg-slate-900/70 border-slate-800',
            soft: 'text-slate-300',
          }
        : {
            page: 'bg-slate-50 text-slate-900',
            card: 'bg-white border-slate-200',
            soft: 'text-slate-600',
          },
    [darkMode],
  );

  return (
    <div className={`min-h-screen ${theme.page}`}>
      <header className="sticky top-0 z-20 backdrop-blur border-b border-slate-700/30">
        <div className="max-w-7xl mx-auto px-6 py-4 flex items-center justify-between">
          <div className="flex items-center gap-2 font-semibold text-lg">
            <Sparkles className="w-5 h-5 text-violet-400" /> StudyTurbo
          </div>
          <button
            className="px-3 py-2 rounded-lg border border-slate-700/40 hover:bg-slate-800/40"
            onClick={() => setDarkMode((v) => !v)}
          >
            {darkMode ? <Sun className="w-4 h-4" /> : <Moon className="w-4 h-4" />}
          </button>
        </div>
      </header>

      <main className="max-w-7xl mx-auto px-6 py-12 space-y-14">
        <section className="grid md:grid-cols-2 gap-8 items-start">
          <div>
            <p className="text-violet-400 font-medium mb-3">AI-powered student productivity platform</p>
            <h1 className="text-4xl md:text-6xl font-bold leading-tight mb-5">StudyTurbo for web, iOS, and Android</h1>
            <p className={`${theme.soft} text-lg`}>
              A modern Notion + ChatGPT style workspace that records lectures, transforms content into study assets,
              and generates visually styled study PDFs ready for export and print.
            </p>
          </div>
          <div className={`rounded-2xl border p-6 ${theme.card}`}>
            <h2 className="text-xl font-semibold mb-4">Core AI capabilities</h2>
            <div className="grid grid-cols-2 gap-3 text-sm">
              <div className="p-3 rounded-lg bg-violet-500/10"><Mic className="w-4 h-4 mb-2" />Speech-to-text</div>
              <div className="p-3 rounded-lg bg-blue-500/10"><FileText className="w-4 h-4 mb-2" />Summarization</div>
              <div className="p-3 rounded-lg bg-emerald-500/10"><Brain className="w-4 h-4 mb-2" />Question generation</div>
              <div className="p-3 rounded-lg bg-amber-500/10"><Headphones className="w-4 h-4 mb-2" />Text-to-speech</div>
            </div>
          </div>
        </section>

        <section className="space-y-5">
          <h2 className="text-3xl font-semibold">1) Full System Architecture</h2>
          <div className="grid lg:grid-cols-3 gap-5">
            {architectureLayers.map((layer) => (
              <article key={layer.title} className={`rounded-2xl border p-5 ${theme.card}`}>
                <h3 className="font-semibold mb-3">{layer.title}</h3>
                <ul className={`space-y-2 text-sm ${theme.soft}`}>
                  {layer.points.map((point) => (
                    <li key={point}>• {point}</li>
                  ))}
                </ul>
              </article>
            ))}
          </div>
        </section>

        <section className="space-y-5">
          <h2 className="text-3xl font-semibold">2) UI/UX Layout</h2>
          <div className={`rounded-2xl border p-6 ${theme.card}`}>
            <ul className={`grid md:grid-cols-2 gap-4 ${theme.soft}`}>
              <li className="flex gap-2"><TabletSmartphone className="w-4 h-4 mt-1" /> Dashboard with smart sidebar, AI inbox, and quick actions.</li>
              <li className="flex gap-2"><Mic className="w-4 h-4 mt-1" /> Smart capture tab for live recording, YouTube links, and PDF ingestion.</li>
              <li className="flex gap-2"><MessageSquare className="w-4 h-4 mt-1" /> Tutor chat docked right with contextual prompts and source grounding.</li>
              <li className="flex gap-2"><FolderTree className="w-4 h-4 mt-1" /> Auto-organized folders with tags, collaborative permissions, and realtime cursors.</li>
              <li className="flex gap-2"><Languages className="w-4 h-4 mt-1" /> Accessibility modes, simplified explanations, and locale-ready typography.</li>
              <li className="flex gap-2"><Sparkles className="w-4 h-4 mt-1" /> Built-in dark/light themes consistent on web and mobile.</li>
            </ul>
          </div>
        </section>

        <section className="space-y-5">
          <h2 className="text-3xl font-semibold">3) Sample Screens</h2>
          <div className="grid md:grid-cols-2 gap-5">
            {sampleScreens.map((screen) => (
              <article key={screen.title} className={`rounded-2xl border p-5 ${theme.card}`}>
                <h3 className="text-xl font-semibold">{screen.title}</h3>
                <p className={`text-sm ${theme.soft} mb-3`}>{screen.subtitle}</p>
                <ul className={`text-sm space-y-2 ${theme.soft}`}>
                  {screen.items.map((item) => (
                    <li key={item}>• {item}</li>
                  ))}
                </ul>
              </article>
            ))}
          </div>
        </section>

        <section className="space-y-5">
          <h2 className="text-3xl font-semibold">4) Styled Study PDF Output Structure</h2>
          <div className={`rounded-2xl border p-6 ${theme.card}`}>
            <ol className={`space-y-2 text-sm ${theme.soft}`}>
              {pdfFlow.map((step) => (
                <li key={step}>{step}</li>
              ))}
            </ol>
            <div className="mt-4 grid md:grid-cols-4 gap-3 text-xs">
              <span className="px-3 py-2 rounded bg-blue-500/20">Blue/Purple/Orange section headers</span>
              <span className="px-3 py-2 rounded bg-amber-500/20">Highlighted keywords + callouts</span>
              <span className="px-3 py-2 rounded bg-emerald-500/20">Definition boxes + comparison tables</span>
              <span className="px-3 py-2 rounded bg-fuchsia-500/20">Title page + dividers + summary boxes</span>
            </div>
          </div>
        </section>

        <section className="space-y-5 pb-10">
          <h2 className="text-3xl font-semibold">5) Code Snippet: PDF Generation Service</h2>
          <pre className="rounded-2xl border border-slate-700/40 bg-black text-emerald-300 p-5 overflow-auto text-xs leading-relaxed">
            <code>{codeSnippet}</code>
          </pre>
        </section>
      </main>
    </div>
  );
}
